<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Laravel\Scout\Searchable;

class Article extends Model
{
	use Searchable;
	
	private $diskName = 'article-images';
	
	protected $visible = [
		'id', 'title', 'content', 'is_draft', 'headerImage', 'sub_category_id', 'subCategory', 'author', 'created_at',
		'tags', 'images', 'deletion_at'
	];
	
	protected $fillable = ['title', 'content', 'sub_category_id', 'user_id', 'deletion_at'];
	
	public function setTitleAttribute($title)
	{
		$this->attributes['title'] = clean($title);
	}
	
	public function setContentAttribute($content){
		$this->attributes['content'] = clean($content);
	}
	
	public function storeImages($images, $isDefaultImgOld, $defaultImgID)
	{
		if (count($images) > 0) {
			foreach ($images as $key => $image) {
				// Store image
				$path = $image->store('', $this->diskName);
				
				// Generate img full url
				$url = Storage::disk($this->diskName)->url($path);
				
				// check if new image is default
				$isDefault = (!$isDefaultImgOld && (int)$defaultImgID === $key) ? true : false;
				
				// Make relationship with article
				$this->images()->create(['url' => $url, 'is_default' => $isDefault]);
			}
		}
	}
	
	// Relationships
	public function author()
	{
		return $this->belongsTo('App\User', 'user_id');
	}
	
	public function subCategory()
	{
		return $this->belongsTo('App\SubCategory', 'sub_category_id');
	}
	
	public function tags()
	{
		return $this->belongsToMany('App\Tag', 'tag_article');
	}
	
	public function detachTags()
	{
		$this->tags()->detach();
	}
	
	public function headerImage()
	{
		return $this->hasOne('App\Image', 'article_id')->where('is_default', true);
	}
	
	public function images()
	{
		return $this->hasMany('App\Image', 'article_id');
	}
	
	public function detachImages()
	{
		$images = $this->images()->get();
		
		if ($images->count() > 0) {
			foreach ($images as $image) {
				$image->article_id = null;
				$image->save();
			}
		}
	}
	
	public function forceDelete()
	{
		$this->detachTags();
		$this->detachImages();
		
		return parent::forceDelete(); // TODO: Change the autogenerated stub
	}
	
	public function syncTags($tags_ids)
	{
		if (isset($tags_ids)) {
			// Associate tags with article
			$tags = Tag::find($tags_ids);
			
			$this->tags()->sync($tags);
		} else {
			// Detach tags
			$this->tags()->detach();
		}
	}
	
	public function syncOldImages($oldImgIDS, $isDefaultImgOld, $defaultImageID)
	{
		$this->dissociateAllOldImages();
		
		if (isset($oldImgIDS) && count($oldImgIDS) > 0) {
			$oldImages = Image::find($oldImgIDS);
			
			// Associate what user left
			$this->images()->saveMany($oldImages);
			
			// Make old img as default
			if ($isDefaultImgOld && in_array($defaultImageID, $oldImgIDS)) {
				Image::makeImageDefault($defaultImageID);
			}
		}
	}
	
	private function dissociateAllOldImages()
	{
		$images = $this->images()->get();
		
		foreach ($images as $image) {
			$image->is_default = false;
			$image->article()->dissociate();
			$image->save();
		}
	}
	
}
