<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
	protected $visible = ['id', 'category_id', 'category', 'name', 'level', 'articles', 'latestEightPublishedArticles'];
	
	protected $fillable = ['category_id', 'name', 'level'];
	
	public function category()
	{
		return $this->belongsTo('App\\Category', 'category_id');
	}
	
	public function articles()
	{
		return $this->hasMany('App\Article', 'sub_category_id');
	}
	
	public function latestEightPublishedArticles()
	{
		return $this->hasMany('App\Article', 'sub_category_id')
			->where('is_draft', 0)
			->with('headerImage')
			->latest()
			->take(8);
	}
	
	public function forceDelete()
	{
		$articles = $this->articles()->get();
		
		$articles->map->forceDelete();
		
		return parent::forceDelete(); // TODO: Change the autogenerated stub
	}
}
