<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Tag extends Model
{
	use Searchable;
	
	protected $visible   = ['id', 'name'];
	protected $fillable = ['name'];
	
	public function articles()
	{
		return $this->belongsToMany('App\Article', 'tag_article');
	}
	
	public function setNameAttribute($name)
	{
		$this->attributes['name'] = clean($name);
	}
	
	public function forceDelete()
	{
		$this->articles()->detach();
		
		return parent::forceDelete(); // TODO: Change the autogenerated stub
	}
}
